# Generated by Django 3.2.5 on 2021-07-25 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=15)),
                ('price', models.FloatField()),
                ('class_type', models.CharField(choices=[('grocery', 'Grocery'), ('enterprise', 'Enterprise')], max_length=20)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.ManyToManyField(default=None, related_name='user_orders', to='myapp.Order')),
                ('original_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='django_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
